### ISSUE TITLE
Add your project in Readme

### ISSUE THREAD

**Issue by anandwana001** [AndroidEngineers/7-day-Android-App-Challenge#18]
Fill the Season 1 Table in the parent Readme

**Comment by anandwana001** [comment]
@Siduchels @nasreekar @sachinsinghd11 @theadityatiwari @abhinavcodedev

**Comment by nasreekar** [comment]
Added mine and created a PR @anandwana001 
https://github.com/AndroidEngineers/7-day-Android-App-Challenge/pull/19

**Comment by Siduchels** [comment]
Added for Meal mate and raised a PR @anandwana001

**Comment by abhinavcodedev** [comment]
Added AniFetch and Raised a PR please check @anandwana001
